# coding: utf-8

"""
    WEX REST APIs

    Authentication methods - Basic Auth - JSON Web Token   - [POST /api/v1/usermgmt/login](#!/User/signinUser)   - [POST /api/v1/usermgmt/logout](#!/User/doLogout) - Python client sample [Download](/docs/wex-python-api.zip) 

    OpenAPI spec version: 12.0.2.417
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import ibmwex
from ibmwex.rest import ApiException
from ibmwex.apis.file_resource_api import FileResourceApi


class TestFileResourceApi(unittest.TestCase):
    """ FileResourceApi unit test stubs """

    def setUp(self):
        self.api = ibmwex.apis.file_resource_api.FileResourceApi()

    def tearDown(self):
        pass

    def test_create(self):
        """
        Test case for create

        Create a file resource
        """
        pass

    def test_delete(self):
        """
        Test case for delete

        Delete a file resource
        """
        pass

    def test_download(self):
        """
        Test case for download

        Fetch a file resource content
        """
        pass

    def test_get(self):
        """
        Test case for get

        List file resource details
        """
        pass

    def test_list(self):
        """
        Test case for list

        List file resources
        """
        pass

    def test_update(self):
        """
        Test case for update

        Update a file resource
        """
        pass

    def test_upload(self):
        """
        Test case for upload

        Update a file resource content
        """
        pass


if __name__ == '__main__':
    unittest.main()
