# coding: utf-8

"""
    WEX REST APIs

    Authentication methods - Basic Auth - JSON Web Token   - [POST /api/v1/usermgmt/login](#!/User/signinUser)   - [POST /api/v1/usermgmt/logout](#!/User/doLogout) - Python client sample [Download](/docs/wex-python-api.zip) 

    OpenAPI spec version: 12.0.2.417
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import ibmwex
from ibmwex.rest import ApiException
from ibmwex.apis.similar_document_ranker_api import SimilarDocumentRankerApi


class TestSimilarDocumentRankerApi(unittest.TestCase):
    """ SimilarDocumentRankerApi unit test stubs """

    def setUp(self):
        self.api = ibmwex.apis.similar_document_ranker_api.SimilarDocumentRankerApi()

    def tearDown(self):
        pass

    def test_cancel_model_training(self):
        """
        Test case for cancel_model_training

        Cancel ranker model training task
        """
        pass

    def test_create(self):
        """
        Test case for create

        Create a similar document ranker
        """
        pass

    def test_create_collection(self):
        """
        Test case for create_collection

        Create and set a collection
        """
        pass

    def test_create_model_from_source_dataset(self):
        """
        Test case for create_model_from_source_dataset

        Create a similar document ranker model
        """
        pass

    def test_delete(self):
        """
        Test case for delete

        Delete a ranker
        """
        pass

    def test_get(self):
        """
        Test case for get

        Show similar document ranker details
        """
        pass

    def test_get_instances(self):
        """
        Test case for get_instances

        List ranker instances where the model deployed
        """
        pass

    def test_get_instances_latest(self):
        """
        Test case for get_instances_latest

        List ranker instances where the latest ranker model deployed
        """
        pass

    def test_get_model(self):
        """
        Test case for get_model

        Show similar document ranker model details
        """
        pass

    def test_get_model_latest(self):
        """
        Test case for get_model_latest

        Show the latest similar document ranker model details
        """
        pass

    def test_get_model_status(self):
        """
        Test case for get_model_status

        Show ranker model status
        """
        pass

    def test_get_resource_set(self):
        """
        Test case for get_resource_set

        Show ranker resource set details
        """
        pass

    def test_get_test_evals(self):
        """
        Test case for get_test_evals

        List ranking evaluation results
        """
        pass

    def test_get_test_rank_eval(self):
        """
        Test case for get_test_rank_eval

        Show ranking evaluation result of the model
        """
        pass

    def test_list(self):
        """
        Test case for list

        List similar document rankers
        """
        pass

    def test_set_model(self):
        """
        Test case for set_model

        Set a similar document ranker model
        """
        pass

    def test_set_resource_set(self):
        """
        Test case for set_resource_set

        Set a ranker resource set
        """
        pass

    def test_update(self):
        """
        Test case for update

        Update a similar document ranker
        """
        pass


if __name__ == '__main__':
    unittest.main()
