# coding: utf-8

"""
    WEX REST APIs

    Authentication methods - Basic Auth - JSON Web Token   - [POST /api/v1/usermgmt/login](#!/User/signinUser)   - [POST /api/v1/usermgmt/logout](#!/User/doLogout) - Python client sample [Download](/docs/wex-python-api.zip) 

    OpenAPI spec version: 12.0.2.417
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import ibmwex
from ibmwex.rest import ApiException
from ibmwex.apis.group_api import GroupApi


class TestGroupApi(unittest.TestCase):
    """ GroupApi unit test stubs """

    def setUp(self):
        self.api = ibmwex.apis.group_api.GroupApi()

    def tearDown(self):
        pass

    def test_create_group(self):
        """
        Test case for create_group

        Create group
        """
        pass

    def test_delete_group(self):
        """
        Test case for delete_group

        Remove group
        """
        pass

    def test_get_group(self):
        """
        Test case for get_group

        Get group
        """
        pass

    def test_list_groups(self):
        """
        Test case for list_groups

        List groups
        """
        pass

    def test_list_user_in_group(self):
        """
        Test case for list_user_in_group

        List users in a group
        """
        pass

    def test_update_group(self):
        """
        Test case for update_group

        Update group
        """
        pass


if __name__ == '__main__':
    unittest.main()
