# coding: utf-8

"""
    WEX REST APIs

    Authentication methods - Basic Auth - JSON Web Token   - [POST /api/v1/usermgmt/login](#!/User/signinUser)   - [POST /api/v1/usermgmt/logout](#!/User/doLogout) - Python client sample [Download](/docs/wex-python-api.zip) 

    OpenAPI spec version: 12.0.2.417
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import ibmwex
from ibmwex.rest import ApiException
from ibmwex.apis.enrichment_api import EnrichmentApi


class TestEnrichmentApi(unittest.TestCase):
    """ EnrichmentApi unit test stubs """

    def setUp(self):
        self.api = ibmwex.apis.enrichment_api.EnrichmentApi()

    def tearDown(self):
        pass

    def test_create(self):
        """
        Test case for create

        Create an enrichment
        """
        pass

    def test_create_facet_dictionary(self):
        """
        Test case for create_facet_dictionary

        Create a dictionary
        """
        pass

    def test_create_from_pear(self):
        """
        Test case for create_from_pear

        Create an enrichment from pear file
        """
        pass

    def test_delete(self):
        """
        Test case for delete

        Delete an enrichment
        """
        pass

    def test_get(self):
        """
        Test case for get

        List enrichment details
        """
        pass

    def test_get_facet_dictionary(self):
        """
        Test case for get_facet_dictionary

        List dictionary details
        """
        pass

    def test_get_facet_dictionary_content(self):
        """
        Test case for get_facet_dictionary_content

        Fetch a dictionary content
        """
        pass

    def test_get_reg_ex_config(self):
        """
        Test case for get_reg_ex_config

        Get the regular expression annotator rules
        """
        pass

    def test_list(self):
        """
        Test case for list

        List enrichments
        """
        pass

    def test_list_facet_dictionaries(self):
        """
        Test case for list_facet_dictionaries

        List dictionaries
        """
        pass

    def test_remove_facet_dictionary(self):
        """
        Test case for remove_facet_dictionary

        Remove a dictionary
        """
        pass

    def test_update(self):
        """
        Test case for update

        Update an enrichment
        """
        pass

    def test_update_facet_dictionary(self):
        """
        Test case for update_facet_dictionary

        Update a dictionary
        """
        pass

    def test_update_facet_dictionary_content(self):
        """
        Test case for update_facet_dictionary_content

        Update a dictionary content
        """
        pass

    def test_update_reg_ex_config(self):
        """
        Test case for update_reg_ex_config

        Create or update regular expression annotator rules
        """
        pass


if __name__ == '__main__':
    unittest.main()
