# coding: utf-8

"""
    WEX REST APIs

    Authentication methods - Basic Auth - JSON Web Token   - [POST /api/v1/usermgmt/login](#!/User/signinUser)   - [POST /api/v1/usermgmt/logout](#!/User/doLogout) - Python client sample [Download](/docs/wex-python-api.zip) 

    OpenAPI spec version: 12.0.2.417
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ClassifierModelStatus(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'state': 'str',
        'creation_progress_of_current_stage': 'float'
    }

    attribute_map = {
        'state': 'state',
        'creation_progress_of_current_stage': 'creationProgressOfCurrentStage'
    }

    def __init__(self, state=None, creation_progress_of_current_stage=None):
        """
        ClassifierModelStatus - a model defined in Swagger
        """

        self._state = None
        self._creation_progress_of_current_stage = None

        if state is not None:
          self.state = state
        if creation_progress_of_current_stage is not None:
          self.creation_progress_of_current_stage = creation_progress_of_current_stage

    @property
    def state(self):
        """
        Gets the state of this ClassifierModelStatus.

        :return: The state of this ClassifierModelStatus.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """
        Sets the state of this ClassifierModelStatus.

        :param state: The state of this ClassifierModelStatus.
        :type: str
        """
        allowed_values = ["INITIAL", "CREATING_DATASETS", "FAILED_TO_CREATE_DATASETS", "CREATING_RESOURCES", "FAILED_TO_CREATE_RESOURCES", "TRAINING", "FAILED_TO_TRAIN", "EVALUATING", "FAILED_TO_EVALUATE", "READY_TO_DEPLOY"]
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def creation_progress_of_current_stage(self):
        """
        Gets the creation_progress_of_current_stage of this ClassifierModelStatus.

        :return: The creation_progress_of_current_stage of this ClassifierModelStatus.
        :rtype: float
        """
        return self._creation_progress_of_current_stage

    @creation_progress_of_current_stage.setter
    def creation_progress_of_current_stage(self, creation_progress_of_current_stage):
        """
        Sets the creation_progress_of_current_stage of this ClassifierModelStatus.

        :param creation_progress_of_current_stage: The creation_progress_of_current_stage of this ClassifierModelStatus.
        :type: float
        """

        self._creation_progress_of_current_stage = creation_progress_of_current_stage

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ClassifierModelStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
