# coding: utf-8

"""
    WEX REST APIs

    Authentication methods - Basic Auth - JSON Web Token   - [POST /api/v1/usermgmt/login](#!/User/signinUser)   - [POST /api/v1/usermgmt/logout](#!/User/doLogout) - Python client sample [Download](/docs/wex-python-api.zip) 

    OpenAPI spec version: 12.0.2.417
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ConfigurationTemplate(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'label': 'str',
        'name': 'str',
        'sections': 'list[ConfigurationSection]'
    }

    attribute_map = {
        'description': 'description',
        'label': 'label',
        'name': 'name',
        'sections': 'sections'
    }

    def __init__(self, description=None, label=None, name=None, sections=None):
        """
        ConfigurationTemplate - a model defined in Swagger
        """

        self._description = None
        self._label = None
        self._name = None
        self._sections = None

        if description is not None:
          self.description = description
        if label is not None:
          self.label = label
        if name is not None:
          self.name = name
        if sections is not None:
          self.sections = sections

    @property
    def description(self):
        """
        Gets the description of this ConfigurationTemplate.

        :return: The description of this ConfigurationTemplate.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this ConfigurationTemplate.

        :param description: The description of this ConfigurationTemplate.
        :type: str
        """

        self._description = description

    @property
    def label(self):
        """
        Gets the label of this ConfigurationTemplate.

        :return: The label of this ConfigurationTemplate.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """
        Sets the label of this ConfigurationTemplate.

        :param label: The label of this ConfigurationTemplate.
        :type: str
        """

        self._label = label

    @property
    def name(self):
        """
        Gets the name of this ConfigurationTemplate.

        :return: The name of this ConfigurationTemplate.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ConfigurationTemplate.

        :param name: The name of this ConfigurationTemplate.
        :type: str
        """

        self._name = name

    @property
    def sections(self):
        """
        Gets the sections of this ConfigurationTemplate.

        :return: The sections of this ConfigurationTemplate.
        :rtype: list[ConfigurationSection]
        """
        return self._sections

    @sections.setter
    def sections(self, sections):
        """
        Sets the sections of this ConfigurationTemplate.

        :param sections: The sections of this ConfigurationTemplate.
        :type: list[ConfigurationSection]
        """

        self._sections = sections

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ConfigurationTemplate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
