# coding: utf-8

"""
    WEX REST APIs

    Authentication methods - Basic Auth - JSON Web Token   - [POST /api/v1/usermgmt/login](#!/User/signinUser)   - [POST /api/v1/usermgmt/logout](#!/User/doLogout) - Python client sample [Download](/docs/wex-python-api.zip) 

    OpenAPI spec version: 12.0.2.417
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CrawlerStatus(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'crawlspace_status': 'list[CrawlspaceStatus]',
        'error_message': 'str',
        'status': 'str',
        'total': 'int'
    }

    attribute_map = {
        'crawlspace_status': 'crawlspaceStatus',
        'error_message': 'errorMessage',
        'status': 'status',
        'total': 'total'
    }

    def __init__(self, crawlspace_status=None, error_message=None, status=None, total=None):
        """
        CrawlerStatus - a model defined in Swagger
        """

        self._crawlspace_status = None
        self._error_message = None
        self._status = None
        self._total = None

        if crawlspace_status is not None:
          self.crawlspace_status = crawlspace_status
        if error_message is not None:
          self.error_message = error_message
        if status is not None:
          self.status = status
        if total is not None:
          self.total = total

    @property
    def crawlspace_status(self):
        """
        Gets the crawlspace_status of this CrawlerStatus.

        :return: The crawlspace_status of this CrawlerStatus.
        :rtype: list[CrawlspaceStatus]
        """
        return self._crawlspace_status

    @crawlspace_status.setter
    def crawlspace_status(self, crawlspace_status):
        """
        Sets the crawlspace_status of this CrawlerStatus.

        :param crawlspace_status: The crawlspace_status of this CrawlerStatus.
        :type: list[CrawlspaceStatus]
        """

        self._crawlspace_status = crawlspace_status

    @property
    def error_message(self):
        """
        Gets the error_message of this CrawlerStatus.

        :return: The error_message of this CrawlerStatus.
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """
        Sets the error_message of this CrawlerStatus.

        :param error_message: The error_message of this CrawlerStatus.
        :type: str
        """

        self._error_message = error_message

    @property
    def status(self):
        """
        Gets the status of this CrawlerStatus.

        :return: The status of this CrawlerStatus.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this CrawlerStatus.

        :param status: The status of this CrawlerStatus.
        :type: str
        """
        allowed_values = ["Waiting", "Crawling", "Stopped", "Completed", "Errored", "Unknown"]
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def total(self):
        """
        Gets the total of this CrawlerStatus.

        :return: The total of this CrawlerStatus.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """
        Sets the total of this CrawlerStatus.

        :param total: The total of this CrawlerStatus.
        :type: int
        """

        self._total = total

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CrawlerStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
