# coding: utf-8

"""
    WEX REST APIs

    Authentication methods - Basic Auth - JSON Web Token   - [POST /api/v1/usermgmt/login](#!/User/signinUser)   - [POST /api/v1/usermgmt/logout](#!/User/doLogout) - Python client sample [Download](/docs/wex-python-api.zip) 

    OpenAPI spec version: 12.0.2.417
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PathComponentType(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'feature_path': 'str',
        'literal': 'str',
        'normalization': 'str'
    }

    attribute_map = {
        'feature_path': 'featurePath',
        'literal': 'literal',
        'normalization': 'normalization'
    }

    def __init__(self, feature_path=None, literal=None, normalization=None):
        """
        PathComponentType - a model defined in Swagger
        """

        self._feature_path = None
        self._literal = None
        self._normalization = None

        if feature_path is not None:
          self.feature_path = feature_path
        if literal is not None:
          self.literal = literal
        if normalization is not None:
          self.normalization = normalization

    @property
    def feature_path(self):
        """
        Gets the feature_path of this PathComponentType.

        :return: The feature_path of this PathComponentType.
        :rtype: str
        """
        return self._feature_path

    @feature_path.setter
    def feature_path(self, feature_path):
        """
        Sets the feature_path of this PathComponentType.

        :param feature_path: The feature_path of this PathComponentType.
        :type: str
        """

        self._feature_path = feature_path

    @property
    def literal(self):
        """
        Gets the literal of this PathComponentType.

        :return: The literal of this PathComponentType.
        :rtype: str
        """
        return self._literal

    @literal.setter
    def literal(self, literal):
        """
        Sets the literal of this PathComponentType.

        :param literal: The literal of this PathComponentType.
        :type: str
        """

        self._literal = literal

    @property
    def normalization(self):
        """
        Gets the normalization of this PathComponentType.

        :return: The normalization of this PathComponentType.
        :rtype: str
        """
        return self._normalization

    @normalization.setter
    def normalization(self, normalization):
        """
        Sets the normalization of this PathComponentType.

        :param normalization: The normalization of this PathComponentType.
        :type: str
        """

        self._normalization = normalization

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PathComponentType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
