# coding: utf-8

"""
    WEX REST APIs

    Authentication methods - Basic Auth - JSON Web Token   - [POST /api/v1/usermgmt/login](#!/User/signinUser)   - [POST /api/v1/usermgmt/logout](#!/User/doLogout) - Python client sample [Download](/docs/wex-python-api.zip) 

    OpenAPI spec version: 12.0.2.417
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SizeInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'size': 'int',
        'timestamp': 'int'
    }

    attribute_map = {
        'id': 'id',
        'size': 'size',
        'timestamp': 'timestamp'
    }

    def __init__(self, id=None, size=None, timestamp=None):
        """
        SizeInfo - a model defined in Swagger
        """

        self._id = None
        self._size = None
        self._timestamp = None

        if id is not None:
          self.id = id
        if size is not None:
          self.size = size
        if timestamp is not None:
          self.timestamp = timestamp

    @property
    def id(self):
        """
        Gets the id of this SizeInfo.
        ID of the object. - Dataset ID if type is dataset - Collectio ID if type is nlp 

        :return: The id of this SizeInfo.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this SizeInfo.
        ID of the object. - Dataset ID if type is dataset - Collectio ID if type is nlp 

        :param id: The id of this SizeInfo.
        :type: str
        """

        self._id = id

    @property
    def size(self):
        """
        Gets the size of this SizeInfo.
        size of the object

        :return: The size of this SizeInfo.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """
        Sets the size of this SizeInfo.
        size of the object

        :param size: The size of this SizeInfo.
        :type: int
        """

        self._size = size

    @property
    def timestamp(self):
        """
        Gets the timestamp of this SizeInfo.
        timestamp for this information

        :return: The timestamp of this SizeInfo.
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """
        Sets the timestamp of this SizeInfo.
        timestamp for this information

        :param timestamp: The timestamp of this SizeInfo.
        :type: int
        """

        self._timestamp = timestamp

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SizeInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
