# coding: utf-8

"""
    WEX REST APIs

    Authentication methods - Basic Auth - JSON Web Token   - [POST /api/v1/usermgmt/login](#!/User/signinUser)   - [POST /api/v1/usermgmt/logout](#!/User/doLogout) - Python client sample [Download](/docs/wex-python-api.zip) 

    OpenAPI spec version: 12.0.2.417
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SystemUsage(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dataset_metrics': 'SystemUsageDatasetMetrics',
        'nlp_metrics': 'SystemUsageNlpMetrics'
    }

    attribute_map = {
        'dataset_metrics': 'datasetMetrics',
        'nlp_metrics': 'nlpMetrics'
    }

    def __init__(self, dataset_metrics=None, nlp_metrics=None):
        """
        SystemUsage - a model defined in Swagger
        """

        self._dataset_metrics = None
        self._nlp_metrics = None

        if dataset_metrics is not None:
          self.dataset_metrics = dataset_metrics
        if nlp_metrics is not None:
          self.nlp_metrics = nlp_metrics

    @property
    def dataset_metrics(self):
        """
        Gets the dataset_metrics of this SystemUsage.

        :return: The dataset_metrics of this SystemUsage.
        :rtype: SystemUsageDatasetMetrics
        """
        return self._dataset_metrics

    @dataset_metrics.setter
    def dataset_metrics(self, dataset_metrics):
        """
        Sets the dataset_metrics of this SystemUsage.

        :param dataset_metrics: The dataset_metrics of this SystemUsage.
        :type: SystemUsageDatasetMetrics
        """

        self._dataset_metrics = dataset_metrics

    @property
    def nlp_metrics(self):
        """
        Gets the nlp_metrics of this SystemUsage.

        :return: The nlp_metrics of this SystemUsage.
        :rtype: SystemUsageNlpMetrics
        """
        return self._nlp_metrics

    @nlp_metrics.setter
    def nlp_metrics(self, nlp_metrics):
        """
        Sets the nlp_metrics of this SystemUsage.

        :param nlp_metrics: The nlp_metrics of this SystemUsage.
        :type: SystemUsageNlpMetrics
        """

        self._nlp_metrics = nlp_metrics

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SystemUsage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
