# coding: utf-8

"""
    WEX REST APIs

    Authentication methods - Basic Auth - JSON Web Token   - [POST /api/v1/usermgmt/login](#!/User/signinUser)   - [POST /api/v1/usermgmt/logout](#!/User/doLogout) - Python client sample [Download](/docs/wex-python-api.zip) 

    OpenAPI spec version: 12.0.2.417
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SystemUsageNlpMetricsCollections(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cid': 'str',
        'count': 'int',
        'input_size': 'int',
        'output_size': 'int',
        'last_update': 'int'
    }

    attribute_map = {
        'cid': 'cid',
        'count': 'count',
        'input_size': 'inputSize',
        'output_size': 'outputSize',
        'last_update': 'lastUpdate'
    }

    def __init__(self, cid=None, count=None, input_size=None, output_size=None, last_update=None):
        """
        SystemUsageNlpMetricsCollections - a model defined in Swagger
        """

        self._cid = None
        self._count = None
        self._input_size = None
        self._output_size = None
        self._last_update = None

        if cid is not None:
          self.cid = cid
        if count is not None:
          self.count = count
        if input_size is not None:
          self.input_size = input_size
        if output_size is not None:
          self.output_size = output_size
        if last_update is not None:
          self.last_update = last_update

    @property
    def cid(self):
        """
        Gets the cid of this SystemUsageNlpMetricsCollections.

        :return: The cid of this SystemUsageNlpMetricsCollections.
        :rtype: str
        """
        return self._cid

    @cid.setter
    def cid(self, cid):
        """
        Sets the cid of this SystemUsageNlpMetricsCollections.

        :param cid: The cid of this SystemUsageNlpMetricsCollections.
        :type: str
        """

        self._cid = cid

    @property
    def count(self):
        """
        Gets the count of this SystemUsageNlpMetricsCollections.

        :return: The count of this SystemUsageNlpMetricsCollections.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """
        Sets the count of this SystemUsageNlpMetricsCollections.

        :param count: The count of this SystemUsageNlpMetricsCollections.
        :type: int
        """

        self._count = count

    @property
    def input_size(self):
        """
        Gets the input_size of this SystemUsageNlpMetricsCollections.

        :return: The input_size of this SystemUsageNlpMetricsCollections.
        :rtype: int
        """
        return self._input_size

    @input_size.setter
    def input_size(self, input_size):
        """
        Sets the input_size of this SystemUsageNlpMetricsCollections.

        :param input_size: The input_size of this SystemUsageNlpMetricsCollections.
        :type: int
        """

        self._input_size = input_size

    @property
    def output_size(self):
        """
        Gets the output_size of this SystemUsageNlpMetricsCollections.

        :return: The output_size of this SystemUsageNlpMetricsCollections.
        :rtype: int
        """
        return self._output_size

    @output_size.setter
    def output_size(self, output_size):
        """
        Sets the output_size of this SystemUsageNlpMetricsCollections.

        :param output_size: The output_size of this SystemUsageNlpMetricsCollections.
        :type: int
        """

        self._output_size = output_size

    @property
    def last_update(self):
        """
        Gets the last_update of this SystemUsageNlpMetricsCollections.

        :return: The last_update of this SystemUsageNlpMetricsCollections.
        :rtype: int
        """
        return self._last_update

    @last_update.setter
    def last_update(self, last_update):
        """
        Sets the last_update of this SystemUsageNlpMetricsCollections.

        :param last_update: The last_update of this SystemUsageNlpMetricsCollections.
        :type: int
        """

        self._last_update = last_update

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SystemUsageNlpMetricsCollections):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
