# coding: utf-8

"""
    WEX REST APIs

    Authentication methods - Basic Auth - JSON Web Token   - [POST /api/v1/usermgmt/login](#!/User/signinUser)   - [POST /api/v1/usermgmt/logout](#!/User/doLogout) - Python client sample [Download](/docs/wex-python-api.zip) 

    OpenAPI spec version: 12.0.2.417
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ValidationMetrics(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'iteration': 'int',
        'loss': 'float',
        'timestamp': 'int'
    }

    attribute_map = {
        'iteration': 'iteration',
        'loss': 'loss',
        'timestamp': 'timestamp'
    }

    def __init__(self, iteration=None, loss=None, timestamp=None):
        """
        ValidationMetrics - a model defined in Swagger
        """

        self._iteration = None
        self._loss = None
        self._timestamp = None

        if iteration is not None:
          self.iteration = iteration
        if loss is not None:
          self.loss = loss
        if timestamp is not None:
          self.timestamp = timestamp

    @property
    def iteration(self):
        """
        Gets the iteration of this ValidationMetrics.

        :return: The iteration of this ValidationMetrics.
        :rtype: int
        """
        return self._iteration

    @iteration.setter
    def iteration(self, iteration):
        """
        Sets the iteration of this ValidationMetrics.

        :param iteration: The iteration of this ValidationMetrics.
        :type: int
        """

        self._iteration = iteration

    @property
    def loss(self):
        """
        Gets the loss of this ValidationMetrics.

        :return: The loss of this ValidationMetrics.
        :rtype: float
        """
        return self._loss

    @loss.setter
    def loss(self, loss):
        """
        Sets the loss of this ValidationMetrics.

        :param loss: The loss of this ValidationMetrics.
        :type: float
        """

        self._loss = loss

    @property
    def timestamp(self):
        """
        Gets the timestamp of this ValidationMetrics.

        :return: The timestamp of this ValidationMetrics.
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """
        Sets the timestamp of this ValidationMetrics.

        :param timestamp: The timestamp of this ValidationMetrics.
        :type: int
        """

        self._timestamp = timestamp

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ValidationMetrics):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
