# coding: utf-8

"""
    WEX REST APIs

    Authentication methods - Basic Auth - JSON Web Token   - [POST /api/v1/usermgmt/login](#!/User/signinUser)   - [POST /api/v1/usermgmt/logout](#!/User/doLogout) - Python client sample [Download](/docs/wex-python-api.zip) 

    OpenAPI spec version: 12.0.2.417
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ZkIngestionStatus(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'active': 'bool',
        'last_modified': 'int',
        'status': 'IngestionStatus'
    }

    attribute_map = {
        'active': 'active',
        'last_modified': 'lastModified',
        'status': 'status'
    }

    def __init__(self, active=None, last_modified=None, status=None):
        """
        ZkIngestionStatus - a model defined in Swagger
        """

        self._active = None
        self._last_modified = None
        self._status = None

        if active is not None:
          self.active = active
        if last_modified is not None:
          self.last_modified = last_modified
        if status is not None:
          self.status = status

    @property
    def active(self):
        """
        Gets the active of this ZkIngestionStatus.

        :return: The active of this ZkIngestionStatus.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """
        Sets the active of this ZkIngestionStatus.

        :param active: The active of this ZkIngestionStatus.
        :type: bool
        """

        self._active = active

    @property
    def last_modified(self):
        """
        Gets the last_modified of this ZkIngestionStatus.

        :return: The last_modified of this ZkIngestionStatus.
        :rtype: int
        """
        return self._last_modified

    @last_modified.setter
    def last_modified(self, last_modified):
        """
        Sets the last_modified of this ZkIngestionStatus.

        :param last_modified: The last_modified of this ZkIngestionStatus.
        :type: int
        """

        self._last_modified = last_modified

    @property
    def status(self):
        """
        Gets the status of this ZkIngestionStatus.

        :return: The status of this ZkIngestionStatus.
        :rtype: IngestionStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this ZkIngestionStatus.

        :param status: The status of this ZkIngestionStatus.
        :type: IngestionStatus
        """

        self._status = status

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ZkIngestionStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
